# Use the official latest Node.js image as the base image (Node.js 18.x is the latest LTS)
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Install dependencies like yarn
RUN npm install -g yarn

# Install project dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy the app source code into the container
COPY . .

# Expose the default React Native port (Optional for web or development environment)
EXPOSE 8081

# Command to run the app
CMD ["yarn", "start"]
