name: CI - Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - '*'  # Trigger on any push to any branch
  pull_request:
    branches:
      - '*'  # Trigger on any PR to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17 (Adoptium)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Use temurin, the new Adoptium distribution

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build the project with Gradle
        run: ./gradlew build -x test  # Skip tests for speed (optional)

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/your-image-name:${{ github.sha }} .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/your-image-name:${{ github.sha }}
