name: CI - Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - '*'  # Trigger on any push to any branch
  pull_request:
    branches:
      - '*'  # Trigger on any PR to any branch

jobs:
  # Stage 1: Build Code
  build_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17 (Adoptium)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          ./gradlew build -x test  # Builds the project, skipping tests for speed

  # Stage 2: Build Docker Image
  build_docker_image:
    needs: build_code  # This job depends on the "build_code" job completing first
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/backend:${{ github.sha }} .

  # Stage 3: Push Docker Image to GitHub Container Registry
  push_docker_image:
    needs: build_docker_image  # This job depends on the "build_docker_image" job completing first
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/backend:${{ github.sha }}
